source "https://rubygems.org"

ruby "4.0.6"

gem "bootsnap", "1.25.0", require: false
gem "aws-sdk-s3", "1.229.0", require: false
gem "dotenv-rails", "3.2.0", groups: [ :development, :test ]
gem "faraday", "2.14.3"
gem "faraday-retry", "2.4.0"
gem "image_processing", "2.0.3"
gem "inertia_rails", "3.22.0"
gem "omniauth", "2.1.4"
gem "omniauth-google-oauth2", "1.2.2"
gem "omniauth-rails_csrf_protection", "2.0.1"
gem "opentelemetry-exporter-otlp", "0.34.1"
gem "opentelemetry-instrumentation-active_job", "0.13.0"
gem "opentelemetry-instrumentation-active_record", "0.13.0"
gem "opentelemetry-instrumentation-faraday", "0.33.0"
gem "opentelemetry-instrumentation-rails", "0.42.0"
gem "opentelemetry-sdk", "1.13.0"
gem "pg", "1.6.3"
gem "puma", "8.0.2"
gem "rails", "8.1.3.1"
gem "ruby-vips", "2.3.0"
gem "solid_queue", "1.7.0"
gem "vite_rails", "3.11.1"

group :development do
  gem "brakeman", "8.0.6", require: false
  gem "bundler-audit", "0.9.3", require: false
  gem "foreman", "0.90.0", require: false
  gem "rubocop-rails-omakase", "1.1.0", require: false
end
