test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= ENV.fetch("ACTIVE_STORAGE_ROOT", Rails.root.join("storage")) %>

s3:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV.fetch("S3_REGION", "us-east-1") %>
  bucket: <%= ENV["S3_BUCKET"] %>
  endpoint: <%= ENV["S3_ENDPOINT"].presence %>
  force_path_style: <%= ENV.fetch("S3_FORCE_PATH_STYLE", "false") == "true" %>
  public: false
